/**
 * CRUSH (Indy/Hoosier — Crush) — varsity page 7, top-left panel, captioned
 * "OUTSIDE VEER".
 *
 * Crush Red runs to the LEFT — to the tight end — and is hand-authored from
 * the scan. Crush Black is its mirror out of Black, generated by `mirrorPlay`.
 *
 * Why left out of Red: the page-7 panel draws Crush out of Red with Y and the
 * L wing to the LEFT and the ball going that way. Outside veer needs a tight
 * end to block down and a wing to arc, so the concept lives on the tight end
 * side. Veer (page 5) goes the other way out of the same set — that pairing is
 * deliberate, not an accident of the scan.
 *
 * Resolving varsity's playside/backside rows to actual players, Crush Red left:
 *   PST = LT · PSG = LG · C = C · BSG = RG · BST = RT
 *   PSW = L (playside wing — he ARCS) · BSW = R (backside wing — PITCH MAN)
 *   Y = playside tight end · X = backside split end
 *   S = dive back · Q = quarterback
 *
 * WHAT MAKES IT "OUTSIDE" VEER, and how it differs from Veer:
 *   - The dive aims OUTSIDE the playside tackle (the C gap, off the tight
 *     end's inside hip) instead of at the playside guard's crack.
 *   - The read key is ONE MAN WIDER. Inside veer reads the first man on or
 *     outside the playside tackle; Crush blocks that man and reads the next
 *     defender out — the one who has to support the pitch.
 *   - The playside tight end works INSIDE (down/climb) and the playside wing
 *     ARCS around the read to the last man out.
 *
 * Arrow-by-arrow transcription of the page-7 panel (its front is the varsity
 * "50" look — E outside the tight end, T head up on the playside tackle, N on
 * the center — which is exactly our 5-2, so `vs['52']` is the literal copy):
 *   L  — runs up past the circled E and caps a block beyond him (arc).
 *   Y  — red arc up and INSIDE over the top of LT, ending in an arrowhead
 *        (a climb, not a block bar) → climbs to the playside backer.
 *   LT — short vertical stem capped on the T head up on him → base block.
 *   LG — short stem up and inside capped just outside the N → down block.
 *   C  — vertical stem capped on the N → the center and playside guard are
 *        both on the nose.
 *   RG — long curve up and playside ending in an ARROWHEAD → climb to a backer.
 *   RT — stem up and inside onto the down lineman in his inside gap.
 *   Q  — flat arrow to the playside, outside the tight end.
 *   S  — arrow up and playside into the line.
 *   R  — orbit squiggle through the heels of Super, then flat and wide away.
 *   X  — blue block marks on the corner over him.
 */

import type {
  Action,
  Assignment,
  FrontId,
  FrontPlan,
  OffPosId,
  Play,
} from '../../types/football'
import { mirrorPlay } from '../../utils/mirror'

/** A block aimed at a defender — no path, so it can never strand a diagram. */
const block = (targetId: string): Action[] => [{ kind: 'block', targetId }]

// ---------------------------------------------------------------------------
// Skill actions — identical against all three fronts.
// ---------------------------------------------------------------------------

/**
 * S: the outside-veer dive. Aim OUTSIDE the playside tackle — the crack
 * between LT and Y — not at the guard. Compare Veer, where he aims at the
 * playside guard.
 */
const S_DIVE: Action[] = [
  {
    kind: 'carry',
    path: [
      { x: -0.6, y: -3.4 },
      { x: -1.6, y: -2.2 },
      { x: -2.6, y: -1.1 },
      { x: -3.5, y: 0.3 },
      { x: -4, y: 2.6 },
      { x: -4.3, y: 5.5 },
    ],
  },
]

/** Q: open playside, ride the mesh, then get FLAT and press the edge. */
const Q_READ: Action[] = [
  {
    kind: 'run',
    path: [
      { x: -1.1, y: -1.7 },
      { x: -2.5, y: -1.9 },
      { x: -4, y: -1.7 },
      { x: -5.4, y: -0.8 },
      { x: -6.4, y: 1.2 },
      { x: -6.8, y: 3.6 },
    ],
  },
]

/**
 * R: the pitch man. Orbit motion through the heels of Super, then arc and hold
 * a 5-by-1 pitch relationship. Wider than Veer's — outside veer starts wider,
 * so the pitch phase starts wider too.
 */
const R_PITCH: Action[] = [
  {
    kind: 'motion',
    path: [
      { x: 4, y: -2.6 },
      { x: 2, y: -4.2 },
      { x: 0, y: -5 },
      { x: -2, y: -4.6 },
      { x: -4, y: -3.8 },
    ],
  },
  {
    kind: 'pitch',
    path: [
      { x: -6.2, y: -2.9 },
      { x: -8.4, y: -1.4 },
      { x: -9.8, y: 0.8 },
    ],
  },
]

/** X: backside — go get the corner on your side. */
const X_CORNER: Action[] = block('C-R')

/** L: the arc. Release around the read key and go get the last man out. */
const L_ARC: Action = {
  kind: 'run',
  path: [
    { x: -7.2, y: -0.5 },
    { x: -8.6, y: 1.6 },
    { x: -9.4, y: 3.8 },
  ],
}

/** Y: inside release, over the top of the tackle's block, then climb. */
const Y_INSIDE: Action = {
  kind: 'run',
  path: [
    { x: -3.9, y: 0.7 },
    { x: -3.2, y: 2.2 },
  ],
}

const SKILL = {
  S: S_DIVE,
  Q: Q_READ,
  R: R_PITCH,
  X: X_CORNER,
} satisfies Partial<Record<OffPosId, Action[]>>

// ---------------------------------------------------------------------------
// Front plans
// ---------------------------------------------------------------------------

/**
 * 4-4. The end is head up on our tight end, so Y blocks him and the READ moves
 * out to the walked-up backer. The wing arcs all the way to the corner.
 */
const vs44: FrontPlan = {
  readKey: 'S-L',
  actions: {
    ...SKILL,
    Y: block('E-L'),
    L: [L_ARC, ...block('C-L')],
    LT: block('B-L'),
    LG: block('T-L'),
    C: block('F'),
    RG: block('T-R'),
    RT: block('B-R'),
  },
  assignments: {
    Y: {
      rule: 'Base the man on you.',
      detail:
        'The end is head up on you in a 4-4. Take him — that is what moves the read out to the backer behind him. Get your hat on his playside number and do not let him cross your face.',
    },
    L: {
      rule: 'Arc around the read — go get the corner.',
      detail:
        'Release outside, run right past the read key (never touch him) and climb to the corner. You are the last block before the pitch turns into a long one.',
    },
    LT: {
      rule: 'Uncovered — step playside, climb to the backer.',
      detail:
        'Nobody on you. Step playside off the guard\'s hip and put your hat on the backer inside. He is the man who fills on the dive.',
    },
    LG: {
      rule: 'Covered — base him.',
      detail: 'The tackle is right on you. Take his playside number and wall him inside.',
    },
    C: {
      rule: 'Step playside. Uncovered — get vertical.',
      detail:
        'Nobody on your nose in an even front. Step playside, run vertical up the middle and take the free safety — the man nobody else has.',
    },
    RG: {
      rule: 'Covered — base him.',
      detail: 'A man is on you on the back side. Take him and never let him chase down the line.',
    },
    RT: {
      rule: 'Uncovered — step playside, climb to the backside backer.',
      detail: 'Step playside first. Nothing in your gap, so climb and cut off the backer chasing from behind.',
    },
  },
}

/**
 * 4-3. Same idea, but nobody is walked up on the edge — the outside backer at
 * four and a half yards is the man who has to support, so he is the read.
 */
const vs43: FrontPlan = {
  readKey: 'B-L',
  actions: {
    ...SKILL,
    Y: block('E-L'),
    L: [L_ARC, ...block('C-L')],
    LT: block('M'),
    LG: block('T-L'),
    C: block('T-R'),
    RG: block('B-R'),
    RT: block('E-R'),
  },
  assignments: {
    Y: {
      rule: 'Base the man on you.',
      detail:
        'The end is head up on you. Block him. The read is the backer behind him — leave that man alone, he is the quarterback\'s.',
    },
    L: {
      rule: 'Arc around the read — go get the corner.',
      detail:
        'Release outside and run past the backer we are reading. Climb to the corner and stay on him.',
    },
    LT: {
      rule: 'Uncovered — step playside, climb to the Mike.',
      detail: 'Nobody on you. Step playside and climb straight to the Mike stacked over the ball.',
    },
    LG: {
      rule: 'Covered — base him.',
      detail: 'The tackle is on your nose. Take his playside number.',
    },
    C: {
      rule: 'Step playside. Uncovered — block back.',
      detail:
        'Nobody on you. Step playside, then take the down man on the back side away from the play. If you miss him he runs the dive down from behind.',
    },
    RG: {
      rule: 'Uncovered — climb to the backside backer.',
      detail: 'The center has the man in your inside gap. Step playside and cut off the backer chasing.',
    },
    RT: {
      rule: 'Base the end on you.',
      detail: 'Backside end is outside you. Take him and hold him — nothing chases us from behind.',
    },
  },
}

/**
 * 5-2 — the arrow-for-arrow copy of the page-7 panel. The end aligns OUTSIDE
 * our tight end, so Y works inside and the end himself is the read.
 */
const vs52: FrontPlan = {
  readKey: 'E-L',
  actions: {
    ...SKILL,
    Y: [Y_INSIDE, ...block('B-L')],
    L: [L_ARC, ...block('C-L')],
    LT: block('T-L'),
    LG: block('N'),
    C: block('N'),
    RG: block('B-R'),
    RT: block('T-R'),
  },
  assignments: {
    Y: {
      rule: 'Inside release — climb to the playside backer.',
      detail:
        'The end outside you is the read key: do not touch him. Step inside, run right over the top of the tackle\'s block and put your hat on the backer. That block is what springs the keep.',
    },
    L: {
      rule: 'Arc around the read — go get the corner.',
      detail:
        'Release outside, run past the end we are reading and climb to the corner. If a safety beats you to the alley, take him instead — block the first jersey that shows outside.',
    },
    LT: {
      rule: 'Base the man on you.',
      detail:
        'Odd front: their tackle is head up on you. Step playside, get your hat across him and wall him off from the ball.',
    },
    LG: {
      rule: 'Down — take the nose with the center.',
      detail:
        'Step inside and get your shoulder on the nose\'s playside number. The center is on him too — you two are one block until the nose is moved, then whoever is free climbs.',
    },
    C: {
      rule: 'Covered — block the nose.',
      detail: 'He is right on you. Take him, and let the guard take his playside half.',
    },
    RG: {
      rule: 'Uncovered — climb to the backside backer.',
      detail: 'Nobody on you in a 5-2. Step playside, then climb and cut off the backer chasing from behind.',
    },
    RT: {
      rule: 'Base the man on you.',
      detail: 'Their tackle is head up on you on the back side. Take him and stay on him.',
    },
  },
}

// ---------------------------------------------------------------------------
// The front-independent teaching table.
// ---------------------------------------------------------------------------

const assignments: Record<OffPosId, Assignment> = {
  LT: {
    rule: 'Covered: base. Uncovered: step playside and climb.',
    detail:
      'You are the playside tackle. If a man is on you, take him — the dive is coming right off your outside hip and he cannot be there. If nobody is on you, step playside and go get a linebacker.',
  },
  LG: {
    rule: 'Covered: base. Uncovered: down, then help on the nose.',
    detail:
      'Playside guard. Take the man on you. If nobody is on you, step inside and get on the nose with the center.',
  },
  C: {
    rule: 'Covered: base the nose. Uncovered: step playside and get vertical.',
    detail:
      'Playside foot first, every time. Covered means block him. Uncovered means climb up the middle or take the down man the play is running away from.',
  },
  RG: {
    rule: 'Covered: base. Uncovered: climb to the backside backer.',
    detail: 'If a man is on you, take him. If not, step playside and cut off the backer who chases us from behind.',
  },
  RT: {
    rule: 'Backside — take the man on or outside you.',
    detail: 'Nothing catches us from behind. Get your hat on him and stay on him until the whistle.',
  },
  Y: {
    rule: 'Block the man on you. Nobody on you — inside release and climb.',
    detail:
      'Playside tight end. If a defender is head up on you, base him and the read moves out to the next man. If he is aligned outside you, he IS the read — release inside him and climb to the backer.',
  },
  L: {
    rule: 'Arc around the read key — block the last man out.',
    detail:
      'You are the playside wing. Release outside, run right past the read key without touching him, and go get the deepest support man on your side — corner or safety, whoever shows. This block turns a five-yard pitch into a long one.',
  },
  R: {
    rule: 'Pitch man. Orbit motion through the heels of Super.',
    detail:
      'Pre-snap motion through the heels of Super, then arc and hold five yards outside the quarterback and one yard behind him. Eyes on the ball the whole way, hands up and soft.',
  },
  S: {
    rule: 'Dive OUTSIDE the playside tackle.',
    detail:
      'This is not Veer. Aim for the crack between the playside tackle and the tight end, not at the guard. Soft fold on the mesh, wave read on the ball: if it stays, it is yours — run downhill. If he pulls it, keep sprinting and take a tackler with you.',
  },
  Q: {
    rule: 'Open playside. Read the key: dive, keep, or pitch.',
    detail:
      'Step playside and pivot on your back foot. Extend the ball behind your back hip. Your key is one man WIDER than on Veer — the first man outside our tight end\'s block, the one who has to support the pitch. If he takes the dive: give it. If he sits: pull it and get flat around the edge. If he takes you: pitch it.',
  },
  X: {
    rule: 'Backside: block the corner.',
    detail:
      'You are alone out there. Get to the corner\'s inside number and stay on him so nothing chases the play from the back side.',
  },
}

const reviewNotes = [
  "CRUSH RUNS TO THE TIGHT END. Page 7 draws Crush out of Red going LEFT — to Y and the L wing — which is the opposite way from Veer out of the same formation. We ship it that way: Crush Red is left, Crush Black is right. Confirm you want it that way and not called to the split-end side.",
  "THE READ. Crush is captioned OUTSIDE VEER, and the circled defender on page 7 is the end aligned OUTSIDE the tight end — one man wider than the circled end on the Veer page. So the rule we teach is: Crush reads the first man outside our tight end's block. Against our 5-2 that is the end (E), which is the literal scan picture. Against the 4-4 the end is head up on Y, so Y blocks him and the read becomes the walked-up backer (S). Against the 4-3 there is nobody walked up, so the read is the outside backer (B) at four and a half yards. Confirm the 4-4 and 4-3 keys — they are our football call, not something the scan draws.",
  "THE PLAYSIDE WING'S BLOCK. On the scan the wing's arrow runs up past the circled end and caps a block just beyond him, in the space where the varsity front draws its $. Our three fronts have no $ on that edge, so we send him to the corner on his side — the last man who can make the tackle on a pitch. If you would rather he take the first safety in the alley, say so and it is a one-line change in all three fronts.",
  "BACKSIDE GUARD vs the 5-2. The scan's arrow from the backside guard is a climb (arrowhead, no block bar) that ends between the two backers. We put him on the BACKSIDE backer because the tight end is already climbing to the playside one. If you want him playside instead, the tight end goes to the safety.",
  "CENTER AND PLAYSIDE GUARD vs the 5-2 are both drawn on the nose on the scan, so both are coded on the nose. Kids should be taught it as one block with two men on it — guard takes the playside half, center takes the man, and whoever comes free climbs.",
  "The page-7 front is the varsity 50 look (end outside the tight end, tackle head up on the playside tackle, nose on the center), which our 5-2 matches almost exactly — that plan is a literal transcription. The 4-4 and 4-3 plans are the same rules resolved against our own fronts and are the parts most worth your eyes.",
  "Page 7 also carries INDY/HOOSIER - DIVE ('automatic give') and INDY/HOOSIER - SPEEDO ('keep or pitch') on the same page. Those are separate calls off the same look and are NOT in this slice. Flagging them so they don't get lost.",
]

export const crushRed: Play = {
  id: 'crush-red',
  name: 'Crush',
  callName: 'Indy/Hoosier — Crush',
  family: 'run',
  formation: 'red',
  direction: 'left',
  ballCarrier: 'S',
  description:
    'Outside veer. Same triple option as Veer, one gap wider: Super dives outside the playside tackle, the tight end works inside, the wing arcs around the read, and the quarterback reads the man who has to support the pitch. Give, keep, or pitch — the defense picks.',
  assignments,
  vs: { '44': vs44, '43': vs43, '52': vs52 } satisfies Record<FrontId, FrontPlan>,
  reviewNotes,
}

/**
 * Crush Black — generated by mirroring Crush Red. No hand corrections were
 * needed: all three of our fronts are left/right symmetric, Black is drawn on
 * page 1 as an exact mirror of Red, and every rule resolves to the mirrored
 * player with the same job. R becomes the playside wing that arcs, L becomes
 * the pitch man, LT/RT and LG/RG swap, and the read key flips side-suffix.
 */
export const crushBlack: Play = mirrorPlay(crushRed, {
  id: 'crush-black',
  formation: 'black',
  description:
    'Crush to the right out of Black. Same outside-veer read, same arc, other side of the ball — L is the pitch man now and R is the wing who arcs.',
  reviewNotes: [
    ...reviewNotes,
    'Crush Black is generated by mirroring Crush Red (app/utils/mirror.ts) with no hand corrections. If any answer above changes, Black changes with it automatically.',
  ],
})

export const crushPlays: Play[] = [crushRed, crushBlack]
