/**
 * VEER (Indy/Hoosier) — varsity page 5 (main diagram + assignment table) and
 * page 6 (vs Even / vs Odd, both directions).
 *
 * Veer Red runs to the RIGHT and is hand-authored from the scans. Veer Black
 * is the mirror of it (page 1 draws Black as Red's mirror), generated by
 * `mirrorPlay` with the overrides stated at the bottom of this file.
 *
 * Resolving varsity's playside/backside rows to actual players, Red right:
 *   PST = RT · PSG = RG · C = C · BSG = LG · BST = LT
 *   PSW = R (playside wing) · BSW = L (backside wing — the PITCH MAN)
 *   Y = backside tight end · X = playside split end
 *   S = dive back · Q = quarterback
 *
 * The read key is the first down defender ON or OUTSIDE the playside tackle:
 * vs our even fronts that's the end (`E-R`); vs the 5-2 it's the tackle head
 * up on the RT (`T-R`), which is why the 5-2 diagram looks different.
 */

import type {
  Action,
  Assignment,
  FrontId,
  FrontPlan,
  OffPosId,
  Play,
} from '../../types/football'
import { mirrorPlay } from '../../utils/mirror'

/** A block aimed at a defender — no path, so it can never strand a diagram. */
const block = (targetId: string): Action[] => [{ kind: 'block', targetId }]

// ---------------------------------------------------------------------------
// Skill actions — identical against all three fronts.
// ---------------------------------------------------------------------------

/**
 * S: dive at the crack (inside leg) of the playside guard, mesh with Q.
 * The scan draws this as a short, clearly angled arrow whose head sits ON the
 * playside guard about ¾ yard behind the LOS — that is the aiming point, not a
 * vertical climb up the middle. We carry it a little past the LOS because he is
 * the ball carrier, but the angle is the guard's inside leg.
 */
const S_DIVE: Action[] = [
  {
    kind: 'carry',
    path: [
      { x: 0.4, y: -3.1 },
      { x: 0.9, y: -1.6 },
      { x: 1.3, y: -0.3 },
      { x: 2, y: 2 },
      { x: 2.6, y: 4.5 },
    ],
  },
]

/**
 * Q: step playside, ride the mesh flat at his own depth, then break upfield at
 * about 45° OUTSIDE the wing — the scan's keep arrow ends wide and shallow
 * (roughly four line-splits outside the ball, barely past the LOS), pressing
 * the pitch, not climbing straight up the C gap.
 */
const Q_READ: Action[] = [
  {
    kind: 'run',
    path: [
      { x: 1, y: -1.8 },
      { x: 2.6, y: -1.9 },
      { x: 4, y: -1.6 },
      { x: 5.4, y: -0.4 },
      { x: 6.4, y: 1.4 },
    ],
  },
]

/**
 * L: the squiggle on the scan. Pre-snap motion through the heels of Super,
 * then arc out and stay 5 yards outside / 1 yard behind the quarterback.
 */
const L_PITCH: Action[] = [
  {
    kind: 'motion',
    path: [
      { x: -4, y: -2.6 },
      { x: -2, y: -4.2 },
      { x: 0, y: -5 },
      { x: 2, y: -4.6 },
      { x: 3.8, y: -3.8 },
    ],
  },
  {
    kind: 'pitch',
    path: [
      { x: 6, y: -3 },
      { x: 8.6, y: -2 },
      { x: 11.4, y: 0.2 },
    ],
  },
]

/** X: playside — go get the corner. */
const X_CORNER: Action[] = block('C-R')

/**
 * Y on the backside Rip. His arrow leaves the tight end going up and INSIDE
 * (toward the ball), curving like the scan, and his bar sets around 3 yards —
 * he is the backside anchor of the wall.
 */
const Y_RIP: Action[] = [
  {
    kind: 'block',
    path: [
      { x: -4.35, y: 0.9 },
      { x: -4.05, y: 2 },
      { x: -3.6, y: 3 },
    ],
  },
]

const SKILL = {
  S: S_DIVE,
  Q: Q_READ,
  L: L_PITCH,
  X: X_CORNER,
} satisfies Partial<Record<OffPosId, Action[]>>

// ---------------------------------------------------------------------------
// Line work shared by the two EVEN fronts (4-4 and 4-3), drawn to Ryan's
// red-line markup of the scan (2026-08-10): the blocks build one rising WALL.
// Every path curves, every bar cuts back toward the backside, and the
// climbers set their bars around the 3–4 yard mark.
//   Backside: LT steps down and takes the down man on the guard; LG climbs
//             to the wall at the backside backer; Y rips inside and anchors
//             the backside of the wall.
//   Playside: RG bases the down man, RT veers inside and climbs to the wall.
// ---------------------------------------------------------------------------

// Each blocker is ONE continuous `block` action — a chained run + block would
// draw a stray arrowhead halfway up the line where the run segment ends.
const EVEN_LINE = {
  Y: Y_RIP,
  // LT pulls: steps down the line behind the guard, comes around the far
  // (playside) side of the man on him, and washes him AWAY from the play —
  // the bar lands on the DT's playside shoulder, pushing backside.
  // Down-lineman bars set a yard PAST the LOS: we block down and drive them
  // back off the line, never stalemate on it.
  LT: [
    {
      kind: 'block',
      path: [
        { x: -1.8, y: 0.1 },
        { x: -0.8, y: 0.5 },
        { x: -0.6, y: 1.2 },
        { x: -1, y: 1.7 },
      ],
    },
  ],
  RG: [
    {
      kind: 'block',
      path: [
        { x: 2.1, y: 0.4 },
        { x: 2.3, y: 1.1 },
        { x: 2, y: 1.6 },
      ],
    },
  ],
  // The wing pins the SAME way vs both even fronts: barely around the read
  // key's outside hip, bar cutting back inside on the first backer that
  // shows. Vs the 4-4 the walked-up outside backer is IGNORED, like the read
  // key — the option handles both.
  R: [
    {
      kind: 'block',
      path: [
        { x: 4.8, y: 0.1 },
        { x: 5.4, y: 1.6 },
        { x: 5.3, y: 3.3 },
        { x: 4.75, y: 4.1 },
      ],
    },
  ],
} satisfies Partial<Record<OffPosId, Action[]>>

// ---------------------------------------------------------------------------
// Front plans
// ---------------------------------------------------------------------------

const vs44: FrontPlan = {
  readKey: 'E-R',
  // Two men on the playside edge are deliberately unblocked — the read-key
  // end and the walked-up outside backer. The option handles both; the
  // diagram rings them dashed so nobody thinks it's a missed assignment.
  ignored: ['E-R', 'O-R'],
  actions: {
    ...SKILL,
    ...EVEN_LINE,
    // Uncovered: get vertical, curve back, and set the bar on the wall around
    // 3–4 yards — on nobody in particular, exactly like the scan.
    C: [
      {
        kind: 'block',
        path: [
          { x: 0.2, y: 1 },
          { x: 0.1, y: 2.2 },
          { x: -0.4, y: 3.3 },
        ],
      },
    ],
    LG: [
      {
        kind: 'block',
        path: [
          { x: -1.2, y: 0.9 },
          { x: -1.5, y: 2.2 },
          { x: -1.7, y: 3.3 },
        ],
      },
    ],
    RT: [
      {
        kind: 'block',
        path: [
          { x: 3.1, y: 1 },
          { x: 2.7, y: 2.6 },
          { x: 2.2, y: 3.5 },
        ],
      },
    ],
  },
  assignments: {
    C: {
      rule: 'Step playside. Uncovered — get vertical and wall off.',
      detail:
        'Nobody on your nose in an even front. Step playside, climb to the second level, and wall off the first jersey that shows. Your block is the middle of the wall — do not chase anybody deep.',
    },
    RT: {
      rule: 'Step inside, veer inside — up to the backer.',
      detail: 'The end outside you is the read key: leave him alone. Release inside him and climb to the backer over the guard.',
    },
    R: {
      rule: 'Tight off the read key — pin the first backer.',
      detail: 'The read key AND the walked-up backer outside you are both left alone — the option takes care of them. Squeeze tight around the read key, barely off his outside hip, and pin the first backer that shows, pushing him back toward the inside. Rule two: if you miss him, hit the near color — find an opponent and block.',
    },
    LT: {
      rule: 'Rip — pull behind the guard, wash his man away from the play.',
      detail: 'Even front, so it\'s Rip. Pull down the line behind the guard, come around the FAR side of the tackle on him, and push him away from the playside — your block lands on his playside shoulder, driving him back where we came from. The guard climbs to the wall.',
    },
    LG: {
      rule: 'Rip — climb to the wall at the backside backer.',
      detail: 'The tackle outside you takes the man on your nose, so you climb. Get to the second level, bend back toward the backside, and set your block on the backer around three to four yards — that is your piece of the wall.',
    },
  },
}

const vs43: FrontPlan = {
  readKey: 'E-R',
  actions: {
    ...SKILL,
    ...EVEN_LINE,
    C: [
      {
        kind: 'block',
        path: [
          { x: 0.2, y: 1 },
          { x: 0.1, y: 2.4 },
          { x: -0.3, y: 3.8 },
        ],
      },
    ],
    LG: [
      {
        kind: 'block',
        path: [
          { x: -1.2, y: 0.9 },
          { x: -1.9, y: 2.4 },
          { x: -3.4, y: 4 },
        ],
      },
    ],
    RT: [
      {
        kind: 'block',
        path: [
          { x: 3.1, y: 1.2 },
          { x: 3, y: 2.6 },
          { x: 2.6, y: 3.7 },
        ],
      },
    ],
  },
  assignments: {
    C: {
      rule: 'Step playside. Uncovered — get vertical to the Mike.',
      detail: 'Even front again, and the Mike is stacked head up on you. Step playside, get vertical, and put your hat on him.',
    },
    RT: {
      rule: 'Step inside, veer inside — climb to the wall.',
      detail: 'Release inside the read key and climb. The Sam is the wing\'s man to pin, so you wall off the first jersey that shows inside him — set your block on the wall around three to four yards.',
    },
    R: {
      rule: 'Tight off the read key — pin the Sam.',
      detail: 'Squeeze tight around the read key — barely off his outside hip — and pin the Sam, pushing him back toward the inside. Rule two: if you miss him, hit the near color — find an opponent and block.',
    },
    LT: {
      rule: 'Rip — pull behind the guard, wash his man away from the play.',
      detail: 'Even front, so it\'s Rip. Pull down the line behind the guard, come around the FAR side of the tackle on him, and push him away from the playside. The guard climbs behind you.',
    },
    LG: {
      rule: 'Rip — climb to the wall at the backside backer.',
      detail: 'The tackle outside you takes the man on your nose, so you climb and bend back to the backer away from the play. The Will is wider in this front, so you have farther to run — go get him.',
    },
  },
}

const vs52: FrontPlan = {
  readKey: 'T-R',
  actions: {
    ...SKILL,
    Y: Y_RIP,
    // Same wall as the even fronts. The scoop puts LG on the nose and frees
    // the center to climb; every bar besides the wing's cuts backside. Bars on
    // down linemen set a yard past the LOS — block down, drive them back.
    LT: [
      {
        kind: 'block',
        path: [
          { x: -2.5, y: 0.3 },
          { x: -2.2, y: 1 },
          { x: -2.5, y: 1.6 },
        ],
      },
    ],
    LG: [
      {
        kind: 'block',
        path: [
          { x: -0.6, y: 0.3 },
          { x: 0.6, y: 1 },
          { x: 0.35, y: 1.6 },
        ],
      },
    ],
    C: [
      {
        kind: 'block',
        path: [
          { x: 0.5, y: 0.8 },
          { x: -0.3, y: 2.2 },
          { x: -1.4, y: 3.5 },
        ],
      },
    ],
    RG: [
      {
        kind: 'block',
        path: [
          { x: 1.6, y: 1 },
          { x: 1.3, y: 2.4 },
          { x: 0.7, y: 3.4 },
        ],
      },
    ],
    RT: [
      {
        kind: 'block',
        path: [
          { x: 2.5, y: 1 },
          { x: 2.4, y: 2.4 },
          { x: 1.8, y: 3.4 },
        ],
      },
    ],
    R: [
      {
        kind: 'block',
        path: [
          { x: 4, y: 0.2 },
          { x: 4.4, y: 0.6 },
          { x: 4.7, y: 0.8 },
        ],
      },
    ],
  },
  assignments: {
    C: {
      rule: 'Step playside. Covered — Scoop with the backside guard.',
      detail: "Odd front: the nose is head up on you. Step playside and take his playside number until the backside guard takes him over — then climb to the wall, bending back to the backside backer around three to four yards. That's Scoop.",
    },
    LG: {
      rule: 'Odd — Scoop with C.',
      detail: 'Step playside and take the nose over so the center can climb. Get your hat on his playside number and push him back toward the backside. If the nose slants away from us, he is yours alone and the center climbs early.',
    },
    LT: {
      rule: 'Rip — take the man on you.',
      detail: 'The tackle is head up on you. Step playside, get your hat across his playside number, and push him back toward the backside — nothing chases us from behind.',
    },
    RG: {
      rule: 'Step inside. Uncovered — climb to the wall.',
      detail: 'Nobody on you in a 5-2. Climb to the second level, bend back toward the backside, and set your block around three to four yards — your piece is the middle of the wall.',
    },
    RT: {
      rule: 'Step inside, veer inside — up to the backer.',
      detail: 'In an odd front the read key is the man head up on YOU. Do not block him. Release inside him, climb to the backer on your side, and bend your block back into the wall.',
    },
    R: {
      rule: 'Tight off the read key — kick out the end.',
      detail: 'Both backers are covered inside, so come tight off the read key and kick the end outside you OUT. Yours is the one block that pushes away from the wall — the ball runs between your kick-out and the wall.',
    },
  },
}

// ---------------------------------------------------------------------------
// The front-independent teaching table (varsity p5, cleaned up).
// ---------------------------------------------------------------------------

const assignments: Record<OffPosId, Assignment> = {
  RT: {
    rule: 'Step inside, veer inside.',
    detail:
      'You never block the read key. Step inside with your playside foot, release inside him, and take the first backer you see.',
  },
  RG: {
    rule: 'Step inside. Covered: base. Uncovered: base the backer.',
    detail: 'If a man is on you, take him. If nobody is on you, step playside and go get a linebacker.',
  },
  C: {
    rule: 'Step playside. Covered: base. Uncovered: get vertical.',
    detail: 'Playside foot first, every time. Covered means block him. Uncovered means climb straight up the middle to the second level.',
  },
  LG: {
    rule: 'Even: Rip with the tackle outside you. Odd: Scoop with C.',
    detail: 'Look at the center\'s nose. Nobody there (even) — Rip: the tackle steps down for the man on you, and you climb to the wall at the backside backer. A nose guard there (odd) — Scoop it with the center.',
  },
  LT: {
    rule: 'Rip with the guard inside you.',
    detail: 'Your first step is DOWN the line behind the guard, never out. Pull around the far side of the man on him, get your hat on his playside number, and push him away from the play; nothing chases us from behind.',
  },
  Y: {
    rule: 'Backside: Rip. (Playside: base the first man outside the read key.)',
    detail:
      'On the back side you Rip: step playside, get inside the end, and cut off the chase. If the play ever comes your way, you base the first defender outside the read key.',
  },
  R: {
    rule: 'Tight off the read key — pin the backer.',
    detail: 'Rule one: squeeze barely around the read key\'s outside hip and PIN the first backer — push him back toward the inside, never chase him upfield. Rule two: if you miss him, hit the near color — find an opponent and block.',
  },
  L: {
    rule: 'Pitch man. Motion through the heels of Super.',
    detail:
      'Pre-snap motion through the heels of Super, then arc and hold a 5-by-1 pitch relationship with the quarterback — five yards outside him, one yard behind. Eyes on the ball the whole way, hands up and soft.',
  },
  S: {
    rule: 'Dive — aim at the crack of the playside guard.',
    detail:
      'Aim for the crack of the playside guard. Soft fold on the mesh, wave read on the ball: if it stays, it is yours — run downhill. If he pulls it, keep sprinting and take a tackler with you.',
  },
  Q: {
    rule: 'Step playside. Read the key: dive, keep, or pitch.',
    detail:
      'Step to playside and pivot on your back foot. Extend the ball behind your back hip. Eyes on the read key — the first man on or outside the playside tackle. If he takes the dive: give it. If he sits: pull it and get vertical in the C gap. If he takes you: press the pitch.',
  },
  X: {
    rule: 'Playside: block the corner.',
    detail:
      'You are the only man out there. Get to the corner\'s outside number and stay on him — that block is the difference between eight yards and a touchdown. On the back side: run your route or work to the safety.',
  },
}

const reviewNotes = [
  "Indy vs Hoosier: pages 5 and 6 title every panel 'INDY/HOOSIER' and never say which is which. Coach Ryan's read: they may not be directions at all — possibly what we call it based on what we see in the defense. Waiting on the director's answer before wiring callName to either play.",
  "The wall (Ryan's red-line markup of the scan, 2026-08-10): the teaching point of veer blocking is one rising WALL. Every blocker's line now CURVES like the original drawing, and every block besides Y's cuts back toward the backside; the climbers — Y, LG, C, and RT — all set their bars around the 3–4 yard mark; the playside wing is NOT a climber, he squeezes around the read key and pins the backer back inside. Y is the mirror image: he rips up and INSIDE (toward the ball) and anchors the backside of the wall at about 3 yards instead of barring on the end. On the Rip that means LT PULLS — down the line behind the guard, around the far side of the DT, bar on the DT's playside shoulder washing him away from the play — and LG climbs to the wall at the backside backer, the reverse of how the first pass authored it. Every blocker is drawn as one continuous curved block stroke; chaining a run into a block puts a stray arrowhead mid-line.",
  "Playside wing (fixed again, Ryan 2026-08-10): rule one everywhere — tight off the read key to pin the LB. He squeezes BARELY around the read key's outside hip (to the right on Red) and pins with his bar pushing back toward the inside, never a deep climb — the SAME stroke vs both even fronts. Vs the 4-4 the playside edge has TWO ignored defenders: the read-key end and the walked-up outside backer; the option handles both, and the wing pins the first backer that shows. Vs the 4-3 the pin lands on the Sam — which ANSWERS the old open question: the Sam is the wing's man, so RT walls off the first jersey inside him instead. Rule two only if he misses: hit the near color — find an opponent and block. The old 4-3 picture ran the wing ten yards deep to the safety; gone.",
  "Ignored defenders (new convention, Ryan 2026-08-10): a FrontPlan can now list `ignored` defender ids — men the scheme deliberately leaves unblocked. They draw with a small dashed grey ring (the read key keeps its red READ ring instead), and the print book's legend explains it. Veer vs the 4-4 rings the walked-up outside backer; the read-key end is listed too but already carries the READ ring. Mirrors automatically.",
  "Vs the 5-2 (odd) we read the down lineman head up on RT, not the end. That is the varsity rule applied to OUR front: 'first man on or outside PST'. Note what the scan actually circles on p6's odd panel — the outside backer — because varsity's odd front aligns its extra lineman INSIDE the tackle, so the first man on/outside their PST is that backer and the tackle base-blocks the man in his B gap. Same rule, different alignment. If you want the 5-2 to look like the scan, move our T to the playside B gap instead of head up and the read flips to the end. Confirm.",
  "p6's two 'vs Odd' panels draw the same backside picture as the 'vs Even' panels — the guard-tackle strokes look copied across. Vs our 5-2 the LT has a man head up on him, so he takes him (varsity's BST rule) instead of stepping down the way the even-front picture shows.",
  "The varsity even front on p6 puts its extra down lineman on the PLAYSIDE guard; our 4-4 and 4-3 use symmetric tackles on both guards so the play mirrors cleanly. The rules resolve the same way, but the picture is not a pixel copy of the scan.",
  "Super's dive (fixed): the scan's dive arrow is SHORT — the arrowhead sits on the playside guard about ¾ yard behind the LOS, which is the aiming point ('crack of PSG'). Ours ran to six yards downfield off a two-yard lateral gain, which drew as a near-vertical climb over the center's head. The path is now angled harder at the guard's inside leg and trimmed to 4½ yards downfield. He is the ball carrier, so we still draw him past the LOS where varsity stops at the mesh.",
  "Quarterback's keep (fixed): the scan rides him FLAT at his own depth to about four line-splits outside the ball and only then breaks upfield at roughly 45°, ending wide and barely past the LOS — 'press the pitch'. Ours turned up early and finished 3½ yards deep and inside the wing, which read as a C-gap dive rather than an option keep. The break point and endpoint now match the drawing.",
  "Pitch man (fixed): with the keep re-measured, L's arc was re-hung to hold the stated 5-by-1 (about five yards outside the quarterback, one yard behind him) at the end of both paths. The scan's pitch arrow actually finishes even wider and still BEHIND the line; we let ours cross the LOS so the diagram shows where the ball goes.",
  "Center vs the 4-4 (fixed — the wall): his old block ran ten yards to the free safety, a vertical spike straight through the middle of the wall. He now curves up and back toward the backside and sets his bar on the wall at about 3½ yards, on nobody in particular — exactly how the scan draws 'Uncovered: Get Vertical'. The free safety is deliberately left unblocked in this picture.",
  "Vs the 5-2 (rebuilt to the wall, Ryan 2026-08-10): same picture as the even fronts — one rising wall, every bar besides the wing's cutting backside. The scoop now resolves with LG taking the nose over (low bar on his playside number) and the CENTER climbing off it, bending back to the backside backer at about 3½ yards — so the old picture of RG crossing the center's face to reach that backer is gone. RG, uncovered, climbs and sets his bar mid-wall around 3½ yards on nobody in particular; RT veers inside the read key up to the playside backer; Y still anchors the backside at 3. The wing KICKS OUT the end — his is the one bar pushing away from the wall, because the lane runs between his kick-out and the wall. Every defender inside is still covered exactly once.",
  "Down-lineman bars sit a yard OFF the line (Ryan, 2026-08-10): every block on a down lineman — the even-front LT pull and RG base, and the 5-2's LT base and LG scoop — sets its bar about a yard past the LOS, beyond the defender's alignment, not at it. The picture is the teaching point: we block DOWN(field) and drive them back off the line; a bar on the LOS reads as a stalemate.",
]

export const veerRed: Play = {
  id: 'veer-red',
  name: 'Veer',
  family: 'run',
  formation: 'red',
  direction: 'right',
  ballCarrier: 'S',
  description:
    'Our bread and butter. Super dives at the crack of the playside guard, the quarterback reads one man and gives, keeps, or pitches, and the backside wing motions across to ride in pitch relationship. Up front the line veers inside and climbs downfield, building a wall for the ball to run behind. Three plays in one — the defense picks which one we run.',
  assignments,
  vs: { '44': vs44, '43': vs43, '52': vs52 } satisfies Record<FrontId, FrontPlan>,
  reviewNotes,
}

/**
 * Veer Black — generated by mirroring Veer Red, then checked panel by panel
 * against varsity page 6's left-hand diagrams.
 *
 * Hand corrections after that check: NONE were needed. Both fronts we built
 * are left/right symmetric and Black is drawn on page 1 as an exact mirror of
 * Red, so every rule resolves to the mirrored player with the same job:
 * BSW is now R (motions right-to-left as the pitch man), PSW is now L, PST is
 * LT, the read key becomes E-L (even) / T-L (odd), and X — now split left —
 * still blocks the corner on his side. Note that page 6's bottom two panels
 * are Veer LEFT out of the RED formation (tight end stays left), which is a
 * different play from Veer Black; they were used to confirm the direction
 * logic — dive at the playside guard, keep outside, pitch arcing wide — not
 * the alignment.
 */
export const veerBlack: Play = mirrorPlay(veerRed, {
  id: 'veer-black',
  formation: 'black',
  description:
    'Veer to the left out of Black. Same read, same pitch relationship, other side of the ball — R is the pitch man now and L is the wing who pins.',
  reviewNotes: [
    ...reviewNotes,
    'Veer Black is generated by mirroring Veer Red (app/utils/mirror.ts) with no hand corrections. If any of the Red answers above change, Black changes with it automatically.',
  ],
})

export const veerPlays: Play[] = [veerRed, veerBlack]
